version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql-spring-learning
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - spring-learning:/var/lib/mysql

volumes:
  spring-learning:
